#!/bin/bash
# test_app 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

set -eux


main() {

    # Fill in your application code here.
    #
    # To report any recognized errors in the correct format in
    # $HOME/job_error.json and exit this script, you can use the
    # dx-jobutil-report-error utility as follows:
    #
    #   dx-jobutil-report-error "My error message"
    #
    # Note however that this entire bash script is executed with -e
    # when running in the cloud, so any line which returns a nonzero
    # exit code will prematurely exit the script; if no error was
    # reported in the job_error.json file, then the failure reason
    # will be AppInternalError with a generic error message.

    # Mount the parent project using dxFUSE
    wget https://github.com/dnanexus/dxfuse/releases/download/v1.1.1/dxfuse-linux
    chmod u+rx ./dxfuse-linux
 
    FUSE_MOUNT=$HOME/projects
    sudo mkdir $FUSE_MOUNT
    mkdir -p $FUSE_MOUNT
    ./dxfuse-linux -verbose 2 $FUSE_MOUNT $DX_PROJECT_CONTEXT_ID 

    #docker run --rm -p 443:8787 -v $FUSE_MOUNT:/mnt/projects -v /home/dnanexus:/home/dnanexus -e DISABLE_AUTH=true rocker/rstudio:4.2.0
    #docker run --rm -p 443:8787 -v $FUSE_MOUNT:/mnt/projects -v /home/dnanexus:/home/dnanexus -e PASSWORD=password bioconductor/bioconductor_docker:RELEASE_3_15
    docker run --rm -p 443:8787 -v $FUSE_MOUNT:/mnt/projects -v /home/dnanexus:/home/dnanexus -e PASSWORD=password shukwong/rstudio_with_gwas_tools:7fecf3332877c4172b006f69f949a28d864c0d84
}
