FROM unbuntu


MAINTAINER wendy wong


RUN  wget https://downloads.rclone.org/v1.51.0/rclone-v1.51.0-linux-amd64.zip && unzip rclone-v1.51.0-linux-amd64.zip
RUN  cp ./rclone-v1.51.0-linux-amd64/rclone /usr/local/bin/
