FROM rocker/rstudio:4.1.0

MAINTAINER wendy wong

#based on https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_tidyverse_4.1.0

ENV PATH="/usr/local/bin/:${PATH}"

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"

RUN apt-get update && \
    apt-get install curl unzip --yes && \
    apt-get clean && \
    curl -O https://downloads.rclone.org/v1.51.0/rclone-v1.51.0-linux-amd64.zip && \
    unzip rclone-v1.51.0-linux-amd64.zip && \
    cp ./rclone-v1.51.0-linux-amd64/rclone /usr/local/bin/

COPY ./install_r_packages.sh /rocker_scripts
RUN chmod +rx /rocker_scripts/install_r_packages.sh && /rocker_scripts/install_r_packages.sh
#RUN /rocker_scripts/install_tidyverse.sh
